api:
  authToken:
door:
  speakerVolume: 60%
  bellIndicatorOutlet: 1
homeMatic:
  rpcServerPorts:
    - 2001
  thermostatValveOpenThreshold: 0.15
homeKit:
  pin: 123-45-678
outlets:
  count: 3
  legacyWifiEnabling: []
  dependencies: {}
apns:
  keyId:
  key:
  teamId:
  topic:
fritzBox:
  host:
  username:
  password:
